# Generated by Django 5.2.10 on 2026-01-10 15:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title_az', models.CharField(blank=True, max_length=120, null=True, verbose_name='Əsas başlıq (AZ)')),
                ('main_title_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Əsas başlıq (EN)')),
                ('main_title_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='Əsas başlıq (RU)')),
                ('second_title_az', models.CharField(blank=True, max_length=80, null=True, verbose_name='Alt başlıq (AZ)')),
                ('second_title_en', models.CharField(blank=True, max_length=80, null=True, verbose_name='Alt başlıq (EN)')),
                ('second_title_ru', models.CharField(blank=True, max_length=80, null=True, verbose_name='Alt başlıq (RU)')),
                ('description_az', models.TextField(validators=[django.core.validators.MaxLengthValidator(8000)], verbose_name='Text (AZ)')),
                ('description_en', models.TextField(validators=[django.core.validators.MaxLengthValidator(8000)], verbose_name='Text (EN)')),
                ('description_ru', models.TextField(validators=[django.core.validators.MaxLengthValidator(8000)], verbose_name='Text (RU)')),
            ],
            options={
                'verbose_name': 'Haqqımızda',
                'verbose_name_plural': 'Haqqımızda',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_az', models.CharField(max_length=255, verbose_name='Ünvan (AZ)')),
                ('address_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ünvan (EN)')),
                ('address_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ünvan (RU)')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('whatsapp_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Whatsapp əlaqə nömrəsi')),
                ('whatsapp_number_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Whatsapp əlaqə nömrəsi 2')),
                ('phone_three', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('linkedn', models.URLField(blank=True, null=True)),
                ('tiktok', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Əlaqə',
                'verbose_name_plural': 'Əlaqələr',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Url')),
                ('name_az', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MaxLengthValidator(120)], verbose_name='Əməkdaş adı (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MaxLengthValidator(120)], verbose_name='Əməkdaş adı (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MaxLengthValidator(120)], verbose_name='Əməkdaş adı (RU)')),
                ('is_active', models.BooleanField(default=False, verbose_name='Əməkdaş aktivliyi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
            ],
            options={
                'verbose_name': 'Əməkdaş',
                'verbose_name_plural': 'Əməkdaşlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kateqoriya adı (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kateqoriya adı (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kateqoriya adı (RU)')),
            ],
            options={
                'verbose_name': 'Kateqoriya adı',
                'verbose_name_plural': 'Kateqoriya adları',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_az', models.CharField(max_length=250, verbose_name='Vakansiya adı (AZ)')),
                ('title_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Vakansiya adı (EN)')),
                ('title_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Vakansiya adı (RU)')),
                ('description_az', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(8000)], verbose_name='Vakansiya haqqında (AZ)')),
                ('description_en', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(8000)], verbose_name='Vakansiya haqqında (EN)')),
                ('description_ru', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(8000)], verbose_name='Vakansiya haqqında (RU)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('is_active', models.BooleanField(default=False, verbose_name='Vakansiya aktivliyi')),
            ],
            options={
                'verbose_name': 'Vakansiya',
                'verbose_name_plural': 'Vakansiyalar',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True, verbose_name='Slug')),
                ('name_az', models.CharField(max_length=250, verbose_name='Ad (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ad (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ad (RU)')),
                ('description_az', models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Lahiyə haqqında (AZ)')),
                ('description_en', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Lahiyə haqqında (EN)')),
                ('description_ru', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Lahiyə haqqında (RU)')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Url')),
                ('is_completed', models.BooleanField(blank=True, null=True, verbose_name='Lahiyən davam edir yoxsa, tamamlanıb')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Lahiyə aktivliyi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Lahiyə yaradılma tarixi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.projectcategory', verbose_name='Kateqoriya')),
            ],
            options={
                'verbose_name': 'Lahiyə',
                'verbose_name_plural': 'Lahiyələr',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Şəkil')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video')),
                ('is_home_page_background_image', models.BooleanField(default=False, verbose_name='Ana səhifəs üçün arxa plan şəkli')),
                ('is_about_page_background_image', models.BooleanField(default=False, verbose_name='Haqqımızda səhifəsi üçü arxa plan şəkli')),
                ('is_partner_background_image', models.BooleanField(default=False, verbose_name='Əməkdaş səhifəsi üçün arxa plan şəkli')),
                ('is_project_page_background_image', models.BooleanField(default=False, verbose_name='Lahiyə səhifəsi üçün arxa plan şəkli')),
                ('is_vacany_page_background_image', models.BooleanField(default=False, verbose_name='Vakansiya səhifəsi üçün arxa plan şəkli')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Image yaradılma tarixi')),
                ('about', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='projects.about', verbose_name='Haqqımızda')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='projects.partner', verbose_name='Əməkdaşlar')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='projects.project', verbose_name='Lahiyə')),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='projects.vacancy', verbose_name='Vakansiyalar')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Medialar',
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='CV')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('is_read', models.BooleanField(default=False, verbose_name='Oxunulması')),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.vacancy', verbose_name='Vakansiya')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CV-lər',
            },
        ),
    ]
