# Generated by Django 5.2.10 on 2026-01-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_completed',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Lahiyən davam edir yoxsa, tamamlanıb'),
        ),
    ]
