# Generated by Django 5.2.10 on 2026-01-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_vacancy_slug_alter_partner_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Oxunulub'),
        ),
    ]
