# Generated by Django 5.2.10 on 2026-01-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_appeal_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_completed',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Lahiyən tamamlanıb'),
        ),
        migrations.AddConstraint(
            model_name='appeal',
            constraint=models.UniqueConstraint(fields=('vacancy', 'cv'), name='unique_cv_per_vacancy'),
        ),
    ]
