# Generated by Django 5.2.10 on 2026-01-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Mail'),
        ),
    ]
