# Generated by Django 5.2.10 on 2026-01-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_appeal_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appeal',
            name='unique_cv_per_vacancy',
        ),
        migrations.AddConstraint(
            model_name='appeal',
            constraint=models.UniqueConstraint(fields=('vacancy', 'email'), name='unique_cv_per_vacancy'),
        ),
    ]
