# Generated by Django 5.2.10 on 2026-01-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_appeal_unique_cv_per_vacancy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeal',
            options={'ordering': ['-created_at'], 'verbose_name': 'CV', 'verbose_name_plural': 'CV-lər'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lahiyə', 'verbose_name_plural': 'Lahiyələr'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vakansiya', 'verbose_name_plural': 'Vakansiyalar'},
        ),
    ]
