# Generated by Django 5.2.10 on 2026-01-15 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_appeal_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_az', models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Deviz cümləsi(AZ)')),
                ('text_en', models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Deviz cümləsi(EN)')),
                ('text_ru', models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Deviz cümləsi(RU)')),
            ],
            options={
                'verbose_name': 'Deviz',
                'verbose_name_plural': 'Devizlər',
            },
        ),
    ]
