# Generated by Django 5.2.10 on 2026-01-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_motto'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='full_name',
            field=models.CharField(blank=True, null=True, verbose_name='Ad Soyad'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Mobil Nömrə'),
        ),
    ]
