# Generated by Django 5.2.10 on 2026-01-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_appeal_full_name_appeal_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_one', models.PositiveIntegerField(verbose_name='Müştəri sayı')),
                ('value_two', models.PositiveIntegerField(verbose_name='Layihələr sayi')),
                ('value_three', models.PositiveIntegerField(verbose_name='Tərəfdaş sayi')),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistikalar',
            },
        ),
        migrations.RemoveConstraint(
            model_name='appeal',
            name='unique_cv_per_vacancy',
        ),
        migrations.AddConstraint(
            model_name='appeal',
            constraint=models.UniqueConstraint(fields=('vacancy', 'email'), name='unique_email_per_vacancy'),
        ),
        migrations.AddConstraint(
            model_name='appeal',
            constraint=models.UniqueConstraint(fields=('vacancy', 'phone_number'), name='unique_phone_per_vacancy'),
        ),
    ]
