# Generated by Django 5.2.10 on 2026-01-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_statistic_remove_appeal_unique_cv_per_vacancy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='is_partner_background_image',
        ),
        migrations.AddField(
            model_name='media',
            name='is_contact_page_background_image',
            field=models.BooleanField(default=False, verbose_name='Əlaqəsi səhifəsi üçün arxa plan şəkli'),
        ),
        migrations.AddField(
            model_name='media',
            name='is_footer_background_image',
            field=models.BooleanField(default=False, verbose_name='Websiten-ın aşağı hissəsi üçün arxa plan şəkli'),
        ),
    ]
