# Generated by Django 5.2.10 on 2026-01-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_media_is_partner_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='partner',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='partner',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='partner',
            name='linkedn',
            field=models.URLField(blank=True, null=True, verbose_name='Linkedn'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='linkedn',
            field=models.URLField(blank=True, null=True, verbose_name='Linkedn'),
        ),
        migrations.AlterField(
            model_name='media',
            name='is_contact_page_background_image',
            field=models.BooleanField(default=False, verbose_name='Əlaqə səhifəsi üçün arxa plan şəkli'),
        ),
    ]
