# Generated by Django 5.2.10 on 2026-01-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_partner_email_partner_facebook_partner_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='tiktok',
            field=models.URLField(blank=True, null=True, verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='partner',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp Nömrəsi'),
        ),
        migrations.AddField(
            model_name='partner',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube'),
        ),
    ]
