# Generated by Django 5.2.10 on 2026-01-19 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_partner_tiktok_partner_whatsapp_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='linkedn',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='tiktok',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='whatsapp_number',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='youtube',
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=80, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.projectcategory', verbose_name='Kateqoriya'),
        ),
    ]
