# Generated by Django 5.2.10 on 2026-01-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_remove_partner_email_remove_partner_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='YouTube Video Linki'),
        ),
    ]
