# Generated by Django 5.2.10 on 2026-01-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_about_youtube_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='youtube_link',
        ),
    ]
