# Generated by Django 5.2.10 on 2026-01-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_remove_about_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='on_main_page',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Ana səhifədə olsun'),
        ),
    ]
