# Generated by Django 5.2.10 on 2026-01-20 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_project_project_date_alter_project_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Layihə', 'verbose_name_plural': 'Layihələr'},
        ),
        migrations.AlterField(
            model_name='project',
            name='description_az',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Layihə haqqında (AZ)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_en',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Layihə haqqında (EN)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_ru',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Layihə haqqında (RU)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Layihə aktivliyi'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_completed',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Layihə tamamlanıb'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_date',
            field=models.DateField(blank=True, null=True, verbose_name='Layihə yaradılma tarixi'),
        ),
    ]
