# Generated by Django 5.2.10 on 2026-01-21 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_project_options_alter_project_description_az_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('-created_at',), 'verbose_name': 'Tərəfdaş', 'verbose_name_plural': 'Tərəfdaşlar'},
        ),
        migrations.AddField(
            model_name='appeal',
            name='info',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Əlavə məlumat'),
        ),
        migrations.AddField(
            model_name='partner',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='partner',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='partner',
            name='linkedn',
            field=models.URLField(blank=True, null=True, verbose_name='Linkedn'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name_az',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MaxLengthValidator(120)], verbose_name='Tərəfdaş adı (AZ)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MaxLengthValidator(120)], verbose_name='Tərəfdaş adı (EN)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name_ru',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MaxLengthValidator(120)], verbose_name='Tərəfdaş adı (RU)'),
        ),
    ]
