# Generated by Django 5.2.10 on 2026-01-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_alter_partner_options_appeal_info_partner_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='url',
        ),
        migrations.AlterField(
            model_name='partner',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='(Instagram)'),
        ),
    ]
