# Generated by Django 5.2.10 on 2026-01-21 10:26

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_remove_partner_url_alter_partner_instagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, null=True, verbose_name='Ad Soyad')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Mail')),
                ('subject', models.CharField(blank=True, max_length=250, null=True, verbose_name='Subyekt')),
                ('info', models.TextField(blank=True, max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Əlavə məlumat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False, verbose_name='Oxunulub')),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Mesajlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameModel(
            old_name='Appeal',
            new_name='AppealVacancy',
        ),
        migrations.AlterModelOptions(
            name='motto',
            options={'verbose_name': 'Deviz', 'verbose_name_plural': 'Deviz'},
        ),
        migrations.AlterField(
            model_name='about',
            name='description_az',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)], verbose_name='Text (AZ)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description_en',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)], verbose_name='Text (EN)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description_ru',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)], verbose_name='Text (RU)'),
        ),
        migrations.AlterField(
            model_name='motto',
            name='text_az',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(220)], verbose_name='Deviz cümləsi(AZ)'),
        ),
        migrations.AlterField(
            model_name='motto',
            name='text_en',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(220)], verbose_name='Deviz cümləsi(EN)'),
        ),
        migrations.AlterField(
            model_name='motto',
            name='text_ru',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(220)], verbose_name='Deviz cümləsi(RU)'),
        ),
    ]
