# Generated by Django 5.2.10 on 2026-01-21 10:40

from django.db import migrations, models


def remove_duplicates(apps, schema_editor):
    """Remove duplicate AppealContact records before adding constraint"""
    AppealContact = apps.get_model('projects', 'AppealContact')
    
    # Hər email və tarix kombinasiyası üçün yalnız ən yeni record-u saxla
    from django.db.models import Max
    
    # Duplicate-ləri tap
    duplicates = AppealContact.objects.values('email', 'created_date').annotate(
        max_id=Max('id')
    ).values_list('email', 'created_date', 'max_id')
    
    # Duplicate-ləri sil (ən yeni olanı saxla)
    for email, created_date, max_id in duplicates:
        AppealContact.objects.filter(
            email=email,
            created_date=created_date
        ).exclude(id=max_id).delete()


def reverse_remove_duplicates(apps, schema_editor):
    """Reverse migration - nothing to do"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_appealcontact_rename_appeal_appealvacancy_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates, reverse_remove_duplicates),
        migrations.AddConstraint(
            model_name='appealcontact',
            constraint=models.UniqueConstraint(fields=('email', 'created_date'), name='unique_email_per_day'),
        ),
    ]
