# Generated by Django 5.2.10 on 2026-01-21 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_appealcontact_unique_email_per_day'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appealcontact',
            name='unique_email_per_day',
        ),
    ]
