# Generated by Django 5.2.10 on 2026-01-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_remove_appealcontact_unique_email_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='speacial_project',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Xüsusi Lahiyə'),
        ),
    ]
