# Generated by Django 5.2.10 on 2026-01-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_project_speacial_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='speacial_project',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Seçilmiş Lahiyə'),
        ),
    ]
