# Generated by Django 5.2.10 on 2026-01-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_alter_project_speacial_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='on_main_page',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ana səhifədə olsun'),
        ),
        migrations.AlterField(
            model_name='project',
            name='speacial_project',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Seçilmiş Lahiyə'),
        ),
    ]
