# Generated by Django 5.2.11 on 2026-02-09 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_alter_project_on_main_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appealvacancy',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeal_set', to='projects.vacancy', verbose_name='Vakansiya'),
        ),
    ]
